version: '3'

services:
  nginx:
    image: nginx:1.19
    volumes:
      - .:/home/app
      - ./docker/nginx/conf/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 80:80
    links:
      - php

  php:
    build: docker/php
    working_dir: /home/app
    volumes:
      - .:/home/app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - .:/home/app
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:6.0-alpine

  smtp:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

  quality-assurance:
    build: docker/quality-assurance
    volumes:
      - .:/project