name: CI

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Up needed docker
        run: docker-compose up -d php db

      - name: Load database
        run: make db-load-fixtures

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: make vendor

      - name: Code quality
        run: make code-quality

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup docker override
        run: make docker-compose.override.yaml

      - name: Up needed docker
        run: docker-compose up -d nginx-proxy nginx redis php db selenium

      - name: Load database
        run: make db-load-fixtures

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: make vendor

      - name: Unit test
        run: make unit-test

#      - name: Behat test
#        run: make behat