name: CI

on:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install project
        run: make install

      - name: Run quality code
        run: make quality-code
